name: mcga
channels:
  - conda-forge
dependencies:
  - python=3.10
  - requests
  - numpy
  - pandas
  - rdkit
  - streamlit
  - pip
  - pip:
    - pubchempy
    - google-generativeai
    - streamlit-ketcher